language: java
install: true
jdk:
  - openjdk11
service:
  - mysql

env:
  - LINE_VERSION=$(echo $TRAVIS_BRANCH | sed "s/line\///")
  - SHORT_HASH=$(git rev-parse --short HEAD)

before_script:
  - mysql -e "DROP DATABASE IF EXISTS flyaktest;"
  - mysql -e "CREATE DATABASE flyaktest;"

script:
  - "./gradlew build"
  - echo $SHORT_HASH
  - echo "$LINE_VERSION-$SHORT_HASH" > build/libs/gitinfo
  - docker build -t flyakorg/api .

after_script:
  - if [ "$TRAVIS_TAG" != "" ];
    then docker tag flyakorg/api flyakorg/api:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push flyakorg/api:latest;
    docker tag flyakorg/api:latest flyakorg/api:$TRAVIS_TAG;
    docker push flyakorg/api:$TRAVIS_TAG;
    fi
  - if [ "$TRAVIS_BRANCH" == "dev" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker tag flyakorg/api flyakorg/api:devel;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push flyakorg/api:devel;
    fi
  - if [[ "$TRAVIS_BRANCH" == "line/"* ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker tag flyakorg/api flyakorg/api:dev-$LINE_VERSION;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push flyakorg/api:dev-$LINE_VERSION;
    fi

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
